//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8109_PRG522SA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reg
    {
        
        public int Id { get; set; }


        [Required(ErrorMessage = "This field is required")]
        public string Email { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string Password_ { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Password_", ErrorMessage = "Confirm pasword does match")]
        public string ConfirmPassword_ { get; set; }
    }
}
